server:
  port: 8080
---
spring:
  profiles:
    active:
      - dev
  sleuth:
    sampler:
    probability: 1.0
  zipkin:
    base-url: http://192.168.0.6:9411/
  jpa:
    show-sql: true
   # hibernate:
   #   ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://192.168.0.6:3306/toures_domain_orden?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: gema
    password: m22102013M..

  application:
    name: toures-balon-orden
